version: "3"

services:
  lava:
    build: .
    restart: always
    env_file:
      - stack.env
    volumes:
      - "./configs:/configs"
    ports:
      - "8084:8084"
    networks:
      - lava

  lavalink:
    image: fredboat/lavalink
    hostname: lavalink
    restart: always
    volumes:
      - "./configs/application.yml:/opt/Lavalink/application.yml:r"
    networks:
      - lava

networks:
  lava:
