version: "3"

services:
  lava:
    image: ghcr.io/nat1anwastaken/lava:latest
    restart: always
    env_file:
      - stack.env
    volumes:
      - "./configs:/lava/configs"
    ports:
      - "8084:8084"
