version: "3"

services:
  lava:
    build: .
    restart: always
    env_file:
      - .env
    environment:
      - TOKEN=$TOKEN
      - SPOTIFY_CLIENT_ID=$SPOTIFY_CLIENT_ID
      - SPOTIFY_CLIENT_SECRET=$SPOTIFY_CLIENT_SECRET
      - SPOTIFY_REDIRECT_URI=$SPOTIFY_REDIRECT_URI
    volumes:
      - "./configs:/configs"
    ports:
      - "8080:8080"
    networks:
      - lava

  lavalink:
    image: fredboat/lavalink
    hostname: lavalink
    restart: always
    volumes:
      - "./configs/application.yml:/opt/Lavalink/application.yml:r"
    networks:
      - lava

networks:
  lava:
